name: 'Mirta Contentful Migration Action'
description: 'Run a Migration against your Contentful space'
outputs:
  environment_url:
    description: 'Contentful environment URL'
  environment_name:
    description: 'Contentful environment name'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'red'
